# This is a sample Dockerfile you can modify to deploy your own app based on ffmpeg  on the GPU
# In order to run Docker in the GPU you will need to install Nvidia-Docker: https://github.com/NVIDIA/nvidia-docker

FROM nvidia/cuda:9.0-cudnn7-devel

